---
services:
  kafka:
    depends_on:
      - zookeeper
    environment:
      CONFLUENT_METRICS_ENABLE: "true"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka:9092"
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: "zookeeper:2181"
      CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_BROKER_ID: 1
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    hostname: kafka
    image: "confluentinc/cp-enterprise-kafka:3.2.1"
    ports:
      - "9092:9092"
  kafka-ws:
    build: "."
    depends_on:
     - zookeeper
     - kafka
     - schema_registry
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http:\\/\\/schema_registry:8081"
      TOPICS: testtopic
    ports:
      - "9093:9093"
  schema_registry:
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
    hostname: schema_registry
    image: "confluentinc/cp-schema-registry:3.2.1"
    ports:
      - "8081:8081"
  zookeeper:
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    hostname: zookeeper
    image: "confluentinc/cp-zookeeper:3.2.1"
    ports:
      - "2181:2181"
version: "2"
